CREATE TABLE IF NOT EXISTS `NPC` (
  `ID` TINYINT(4),
  `NOMBRE`  TEXT,
  `SPRITE` TEXT,
  `DIALOGO` TEXT,
  `X` INT(2),
  `Y` INT(2),
  `WIDTH` INT(2),
  `HEIGHT` INT(2),
  `INDICE` INT(2),
  PRIMARY KEY (`ID`,`NOMBRE`)
)